name: List services in GCP
on:
  push:
  workflow_dispatch:


jobs:
  Get_OIDC_ID_token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: 'actions/checkout@v3'
    - id: 'auth'
      name: 'Authenticate to GCP'
      uses: 'google-github-actions/auth@v0'
      with:
          create_credentials_file: 'true'
          workload_identity_provider: 'projects/129494882920/locations/global/workloadIdentityPools/test-pool-1/providers/my-provider'
          service_account: 'test-user-1@focused-sprite-368710.iam.gserviceaccount.com'
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'
    - id: 'gcloud'
      name: 'gcloud'
      run: gcloud info
    - id: 'bq'
      name: 'bq'
      run: bq ls
